### ISSUE TITLE
Doesn't show up on in IntelliJ IDEA 2016

### ISSUE THREAD

**Issue by datbayev** [fadeyev/intellijcoder#15]
I've installed the plugin, it was working on previous version of IDE, but on newest Community Edition one it doesn't even show up in View --> Tool Windows.
My IDE version:
IntelliJ IDEA 2016.2.5
Build #IC-162.2228.15, built on October 14, 2016
JRE: 1.8.0_112-release-287-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Screenshot from View --> Tool Windows below:
![screen shot 2016-11-19 at 11 05 07 pm](https://cloud.githubusercontent.com/assets/457089/20458853/bf6a55fc-aeb0-11e6-82e8-56449fd28c76.png)

IntelliJCoder has version 2.1:
![screen shot 2016-11-19 at 11 35 31 pm](https://cloud.githubusercontent.com/assets/457089/20458863/ee0b1360-aeb0-11e6-9f72-542473714834.png)

**Comment by fadeyev** [comment]
Main toolbar is hidden by default in new versions of IDEA. You need to enable it explicitly. Though it's mentioned in the usage section, I'll try to highlight it. Thanks for the report.
