### ISSUE TITLE
Array of long in tests should have `L`.

### ISSUE THREAD

**Issue by codenut** [fadeyev/intellijcoder#16]
Hello,

Thank you for such an awesome plugin. I was using this plugin during SRM 735 and I faced an issue on the Medium Div 1 problem.

The input is an array of `long` integers and the test has an error because the some of the values in the array exceeds `int32`. Inorder to fix this an `L` should be added for each element of the array.

**Comment by fadeyev** [comment]
Thank you very much for the pull request. Merged and released in version 2.2
