### ISSUE TITLE
Update to latest Arena 2022

### ISSUE THREAD

**Issue by tausiq** [fadeyev/intellijcoder#20]
Topcoder Arena Applet has been updated in 2022. Current version: 2022-1.0, released on Nov 10, 2022. 

The previous Arena Applet, bundled with this project, is version: 7.1.3, released on Aug 2014. The user can't log in using this version anymore. It always shows a "Your login request timed out." error. 

 If we could update Arena to the latest version, all should be working as expected. Thanks!

**Comment by fadeyev** [comment]
Uploaded a new version to Jetbrains Marketplace - should be available within 2-3 days.

**Comment by tausiq** [comment]
Thanks @fadeyev for your quick response and taking prompt action. The update is already released. 

However the plugins is not getting loaded (doesn't show the Topcoder arena icon in menubar) and throwing an error. I have created a separate issue for that. Could you please take a look when you are available. Thanks!

**Comment by fadeyev** [comment]
My bad. 
I've uploaded a working version now. Please update the plugin as soon as it's approved.

**Comment by tausiq** [comment]
Hi @fadeyev, the update is released and all is working as expected. Thank you for your prompt reply and fixes. I appreciate your effort.
